attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        electricity: 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U11
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 44
          - 4
          - 8
        - false
        - !!binary |
          ZQAAAGwAAABlAAAAYwAAAHQAAAByAAAAaQAAAGMAAABpAAAAdAAAAHkAAAA=
      warn: true
    group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_: &id004
        electricity: 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - U11
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - 44
          - 4
          - 8
        - false
        - !!binary |
          ZQAAAGwAAABlAAAAYwAAAHQAAAByAAAAaQAAAGMAAABpAAAAdAAAAHkAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group
  lags: null
  max_encoder_length: 168
  max_prediction_length: 24
  min_encoder_length: 168
  min_prediction_idx: !!python/object/apply:numpy.core.multiarray.scalar
  - &id002 !!python/object/apply:numpy.dtype
    args:
    - i8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 24
  predict_mode: false
  randomize_length: null
  scalers:
    time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.6.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAJDF5UA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        WlwBAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          SbBXJ94j2UA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          VVV1UTPAw0E=
      with_mean: true
      with_std: true
  static_categoricals:
  - group
  static_reals: null
  target: Price
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      me+II5cSS0A=
    max_length: null
    method: standard
    method_kwargs: {}
    scale_: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      VniJTdurUEA=
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - time_idx
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - Price
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels:
  group: *id004
embedding_paddings: []
embedding_sizes:
  group: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.03
log_gradient_flow: false
log_interval: 2
log_val_interval: null
lstm_layers: 1
max_encoder_length: 168
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- group
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
time_varying_reals_encoder:
- time_idx
- Price
weight_decay: 0.0
x_categoricals:
- group
x_reals:
- time_idx
- Price
